language: python

matrix:
  include:
    - python: "3.6"
      language: generic-covered
      os: osx
      env: pyver=3.6 pydist=macpython

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # conda channels
  - conda config --append channels conda-forge
  - conda config --append channels cmutel
  - conda config --append channels haasad

  # conda build
  - conda build ./sip
  - conda build ./pyqt

  # Create environment
  - conda create -q -n test-environment python=$pyver pytest;
  - source activate test-environment
  - conda install --use-local sip
  - conda install --use-local pyqt

script:
  - echo "ready for upload"

after_success:
  - conda install anaconda-client;
  - cp /Users/travis/miniconda/conda-bld/osx-64/*.tar.bz2 .
  - anaconda -t $CONDA_TOKEN upload --force sip*.tar.bz2
  - anaconda -t $CONDA_TOKEN upload --force pyqt*.tar.bz2
        

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
